<?php

$autorise = array('constructions', 'decouvertedujeu', 'faq', 'partenaires', 
                  'conditionsgeneralesutilisation', 'quelquesmotssurlesite', 
                  'equipedusite', 'plandusite', 'recrutement', 'premierspas', 
                  'lesattaques', 'lestemples', 'generalitesalliances', 
                  'lesespionnages', 'lesguerresetpactes', 'lemarche', 
                  'lesressources', 'lesfaveurs', 'questionsfrequentes', 
                  'quelquesregles', 'classementdesjoueurs', 
                  'classementdesalliances', 'classements', 'profilsjoueur', 
                  'profilsalliance', 'membrealliance', 'passerenrevue', 
                  'archives', 'alliance', 'construire', 'armurerie', 'tresor', 
                  'donnerunefaveur', 'marcheaudetails', 
                  'messagerie', 'auteldesdieux', 'temples', 'statues', 
                  'prieres', 'listenoire', 'amis', 'pagecontact', 
                  'parrainage', 'bibliotheque', 'pause', 'adressemail', 
                  'motdepasse', 'informationspersonnelles', 'jeux', 
                  'attaquer', 'engager', 'mesattaques', 'strategiedefensive', 
                  'strategieoffensive', 'archivesdemessagerie', 'boiteenvoie', 
                  'nouveaumessage', 'details', 'marchedegros', 'vendre', 
                  'licences', 'mesventes', 'honneur', 'vosobjectifs', 
                  'joueursconnectes', 'lesalliances', 'lire', 
                  'erreur', 'creervotrealliance', 'postuler', 'carremagique', 
                  'des', 'bataillesnavales', 'javelot', 'biges', 'quadriges', 
                  'dissoudre', 'sortieurgence', 'quitter', 'archivesalliance', 
                  'gestionmembres', 'cotisations', 'obtenirdesfaveurs', 
                  'faveurerreur', 'faveurs', 'faveurvalide', 'permalien', 
                  'modifiertemples', 'missives', 'combattitans', 'abonnement', 
                  'gestionmeteo', 'loto', 'sondage', 'actualites', 'dons', 
                  'listebataillesnavales', 'creerunebataillenavale', 'oracle', 
                  'partie', 'ticket', 'soutien', 'teamspeak', 'messucces', 
                  'allianceexistepas', 'missions', 'archivecommerce', 'succes',
                  'calendrier_avent', 'jeu', 'animations', 'trouverpaires',
                  'arbredesdieux', 'evenements', 'monstres', 'bonus',
                  'classementghonneur', 'arbre', 'ecrire_alliance',
                  'profilmonalliance', 'donner', 'coffre', 'calendrier',
                  'archives_alliance', 'guerres', 'pactes', 'nommer',
                  'recrutements', 'niveau', 'tour_de_force',
                  'demande', 'sanctuaires', 'changer_grandchef',
                  'contrats', 'valide', 'blocus');

?>
